age <- c(1,3,5,2,11,9,3,9,12,3)
weight <- c(4.4,5.3,7.2,5.2,8.5,7.3,6.0,10.4,10.2,6.1)
mean(weight)
sd(weight)
cor(age,weight)
plot(age,weight)
getwd()
setwd("C:/Users/ashwi/Desktop/Ashwin/Data_mining_Concepts")
ls()
options()
history(2)
library()
.libPaths()
search()
install.packages("gclus")
help(package = "gclus")
help.start()
install.packages("vcd")
library(vcd)
data("Arthritis")
Arthritis
help(Arthritis)
example(Arthritis)
