pdf("mygraph.pdf")
cars<- mtcars
plot(cars$wt,cars$mpg)
with(cars,{abline(lm(mpg~wt))})
title("Regression of MPG on weight")
dev.off()
dose  <- c(20, 30, 40, 45, 60)
drugA <- c(16, 20, 27, 40, 60)
drugB <- c(15, 18, 25, 31, 40)
plot(dose,drugA,type = "b")
help(plot)
opar<-par(no.readonly = TRUE)
opar
help(par)
par(lty = 2,pch = 17)
plot(dose,drugA,type = "b")
par(opar)
plot(dose,drugA,type = "b")
plot(dose,drugA,type = "b",lty = 2,pch = 17,cex = 1.5,lwd = 2,col = c("blue", brewer.pal(3,"BuGn")))
install.packages("RColorBrewer")
library(RColorBrewer)
help(RColorBrewer)
n <- 7
mycolors <- brewer.pal(n, "Set2")
bar<-c(1,2,3,4,5,6,7,8,9)
barplot(bar, col=mycolors)
n <- 10
mycolors <- rainbow(n)
pie(rep(1, n), labels=mycolors, col=mycolors)
mygrays <- gray(0:n/n)
pie(rep(1, n), labels=mygrays, col=mygrays)
par(font.lab=3, cex.lab=1.5, font.main=4, cex.main=2)
barplot(bar , col= rainbow(10) , main = "Bar plot",xlab = "X-axis",ylab="y-axis")
par(opar)
barplot(bar , col= rainbow(10) , main = "Bar plot",xlab = "X-axis",ylab="y-axis")
