SA<-read.csv('SystemAdministrators_csv.csv')
plot(SA$Experience,SA$Training,col=SA$Completed.task)
plot(SA$Experience,SA$Training,col = c('red','blue'))
plot(SA$Experience,SA$Training,col = c('red','blue','green'))
logit.reg<-glm(Completed.task~.,data = SA,family = 'binomial')
options(scipen = 999)
summary(logit.reg)
fitted.result<-predict(logit.reg,newdata = SA,type = 'response')
prob<-ifelse(fitted.result>0.5,"YES","NO")
table(prob,SA$Completed.task)
prob1<-ifelse(fitted.result>0.7,"YES","NO")
table(prob1,SA$Completed.task)
prob2<-ifelse(fitted.result>0.3,"YES","NO")
table(prob2,SA$Completed.task)
summary(logit.reg)
